// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLsisKIzuCPjR4SoDh52UH90YuYmzXJkM',
    appId: '1:306541753546:web:49b1333f1933083d59f033',
    messagingSenderId: '306541753546',
    projectId: 'agric-hub-7f633',
    authDomain: 'agric-hub-7f633.firebaseapp.com',
    storageBucket: 'agric-hub-7f633.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATDVkG-YddtZkoxFAzSsjywbk4kjT3lHM',
    appId: '1:306541753546:android:74892580e427ec0359f033',
    messagingSenderId: '306541753546',
    projectId: 'agric-hub-7f633',
    storageBucket: 'agric-hub-7f633.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKs-D_l8mjWtsDfJKh4JlJ-pvAXfBi1nI',
    appId: '1:306541753546:ios:f566a7ca80938da059f033',
    messagingSenderId: '306541753546',
    projectId: 'agric-hub-7f633',
    storageBucket: 'agric-hub-7f633.appspot.com',
    iosBundleId: 'com.example.firmerCity',
  );
}
